version: '3.8'

services:
  # API Gateway
  nginx:
    build:
      context: ./BACKEND/nginx
      dockerfile: Dockerfile
    container_name: de_an_nginx
    ports:
      - "8090:8090"  # Single entry point for all backend services
    depends_on:
      - auth
      - be_admin
      - be_chatbot
      - be_preprocess
      - ml
    networks:
      - de_an_network
    restart: unless-stopped

  # Backend Services
  auth:
    build:
      context: ./BACKEND/AUTH
      dockerfile: Dockerfile
    container_name: de_an_auth
    expose:
      - "8888"  # Only exposed to internal network
    volumes:
      - ./BACKEND/AUTH/app:/code/app
      - ./BACKEND/AUTH/config:/code/config
      - ./BACKEND/AUTH/logs:/code/logs
    environment:
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

  be_admin:
    build:
      context: ./BACKEND/BE_ADMIN
      dockerfile: Dockerfile
    container_name: de_an_admin
    expose:
      - "8888"  # Only exposed to internal network
    volumes:
      - ./BACKEND/BE_ADMIN/app:/code/app
      - ./BACKEND/BE_ADMIN/config:/code/config
      - ./BACKEND/BE_ADMIN/logs:/code/logs
    environment:
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

  be_chatbot:
    build:
      context: ./BACKEND/BE_CHATBOT
      dockerfile: Dockerfile
    container_name: de_an_chatbot
    expose:
      - "8888"  # Only exposed to internal network
    volumes:
      - ./BACKEND/BE_CHATBOT/app:/code/app
      - ./BACKEND/BE_CHATBOT/config:/code/config
      - ./BACKEND/BE_CHATBOT/logs:/code/logs
    environment:
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

  be_preprocess:
    build:
      context: ./BACKEND/BE_PREPROCESS
      dockerfile: Dockerfile
    container_name: de_an_preprocess
    expose:
      - "8888"  # Only exposed to internal network
    volumes:
      - ./BACKEND/BE_PREPROCESS/app:/code/app
      - ./BACKEND/BE_PREPROCESS/config:/code/config
      - ./BACKEND/BE_PREPROCESS/logs:/code/logs
    environment:
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

  ml:
    build:
      context: ./BACKEND/ML
      dockerfile: Dockerfile
    container_name: de_an_ml
    expose:
      - "8888"  # Only exposed to internal network
    volumes:
      - ./BACKEND/ML/artifacts:/app/artifacts
      - ./BACKEND/ML/logs:/app/logs
      - ./BACKEND/ML/plots:/app/plots
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped
    
  # Frontend placeholder - uncomment and configure when ready
  # frontend:
  #   build:
  #     context: ./FRONTEND
  #     dockerfile: Dockerfile
  #   container_name: de_an_frontend
  #   ports:
  #     - "3000:3000"  # Typical React/Next.js port
  #   volumes:
  #     - ./FRONTEND:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_API_URL=http://localhost:8090  # Points to the API gateway
  #   networks:
  #     - de_an_network
  #   restart: unless-stopped

networks:
  de_an_network:
    driver: bridge

volumes:
  auth_logs:
  admin_logs:
  chatbot_logs:
  preprocess_logs:
  ml_artifacts:
  ml_logs:
  ml_plots: 