[project]
name = "ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.40.4",
    "chardet>=5.2.0",
    "contractions>=0.1.73",
    "dagshub>=0.6.2",
    "ensure>=1.0.4",
    "fastapi>=0.116.1",
    "imbalanced-learn>=0.12.4",
    "joblib>=1.5.1",
    "langchain-core>=0.3.73",
    "matplotlib>=3.10.5",
    "mlflow==2.7.0",
    "numpy>=1.23.5,<2.0",
    "pandas>=2.3.1",
    "plotly>=5.24.1",
    "pydantic>=2.11.7",
    "python-box>=7.3.2",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "pyyaml>=6.0.2",
    "s3fs>=0.4.2",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "tensorflow>=2.14.0",
    "tqdm>=4.67.1",
    "typing-extensions>=4.14.1",
    "uvicorn>=0.35.0",
]
