version: '3.8'

services:
  # Nginx reverse proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: de_an_nginx
    ports:
      - "8090:8090"
    depends_on:
      - auth
      - be_admin
      - be_chatbot
      - be_preprocess
      - ml
    networks:
      - de_an_network
    restart: unless-stopped

  auth:
    build:
      context: ./AUTH
      dockerfile: Dockerfile
    container_name: de_an_auth
    # No public port mapping - only accessible through nginx
    expose:
      - "8888"
    volumes:
      - ./AUTH/logs:/code/logs
    environment:
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

  be_admin:
    build:
      context: ./BE_ADMIN
      dockerfile: Dockerfile
    container_name: de_an_admin
    # No public port mapping - only accessible through nginx
    expose:
      - "8888"
    volumes:
      - ./BE_ADMIN/logs:/code/logs
    environment:
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

  be_chatbot:
    build:
      context: ./BE_CHATBOT
      dockerfile: Dockerfile
    container_name: de_an_chatbot
    # No public port mapping - only accessible through nginx
    expose:
      - "8888"
    volumes:
      - ./BE_CHATBOT/logs:/code/logs
    environment:
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

  be_preprocess:
    build:
      context: ./BE_PREPROCESS
      dockerfile: Dockerfile
    container_name: de_an_preprocess
    # No public port mapping - only accessible through nginx
    expose:
      - "8888"
    volumes:
      - ./BE_PREPROCESS/logs:/code/logs
    environment:
      - PYTHONPATH=/code
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

  ml:
    build:
      context: ./ML
      dockerfile: Dockerfile
    container_name: de_an_ml
    # No public port mapping - only accessible through nginx
    expose:
      - "8888"
    volumes:
      - ./ML/artifacts:/app/artifacts
      - ./ML/logs:/app/logs
      - ./ML/plots:/app/plots
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - de_an_network
    restart: unless-stopped

networks:
  de_an_network:
    driver: bridge

volumes:
  auth_logs:
  admin_logs:
  chatbot_logs:
  preprocess_logs:
  ml_artifacts:
  ml_logs:
  ml_plots:
