artifacts_root: artifacts

# Churn model configuration
churn_data_ingestion:
  root_dir: artifacts/churn/data_ingestion
  data_version_dir: artifacts/churn/data_version
  local_data_file: artifacts/churn/data_ingestion/input_raw.csv
  test_size: 0.2
  random_state: 42
  bucket_name: ml-dataversion

churn_prepare_base_model:
  model_version_dir: artifacts/churn/model_version
  data_version_dir: artifacts/churn/data_version
  criterion: entropy
  max_depth: 30 
  max_features: log2
  min_samples_leaf: 2
  n_estimators: 500
  random_state: 42

churn_training:
  model_version_dir: artifacts/churn/model_version
  data_version_dir: artifacts/churn/data_version

churn_evaluation:
  model_version_dir: artifacts/churn/model_version
  data_version_dir: artifacts/churn/data_version
  evaluation_dir: artifacts/churn/evaluation

churn_cloud_storage_push:
  root_dir: artifacts
  bucket_name: ml-dataversion
  data_version_dir: artifacts/churn/data_version  
  evaluation_dir: artifacts/churn/evaluation 

churn_mlflow_config:
  dagshub_username: Teungtran
  dagshub_repo_name: churn_mlops
  tracking_uri: https://dagshub.com/Teungtran/churn_mlops.mlflow
  experiment_name: Churn_model_training_cycle

# Sentiment model configuration
sentiment_data_ingestion:
  root_dir: artifacts/sentiment/data_ingestion
  data_version_dir: artifacts/sentiment/data_version
  local_data_file: artifacts/sentiment/data_ingestion/input_raw.csv
  test_size: 0.2
  random_state: 42
  bucket_name: ml-dataversion

sentiment_prepare_base_model:
  model_version_dir: artifacts/sentiment/model_version
  data_version_dir: artifacts/sentiment/data_version
  random_state: 42

sentiment_training:
  model_version_dir: artifacts/sentiment/model_version
  data_version_dir: artifacts/sentiment/data_version

sentiment_evaluation:
  model_version_dir: artifacts/sentiment/model_version
  data_version_dir: artifacts/sentiment/data_version
  evaluation_dir: artifacts/sentiment/evaluation

sentiment_cloud_storage_push:
  root_dir: artifacts
  bucket_name: sentimentdataversion
  data_version_dir: artifacts/sentiment/data_version  
  evaluation_dir: artifacts/sentiment/evaluation 

sentiment_mlflow_config:
  dagshub_username: Teungtran
  dagshub_repo_name: sentiment_mlops
  tracking_uri: https://dagshub.com/Teungtran/sentiment_mlops.mlflow
  experiment_name: Sentiment_model_training_cycle

# Segmentation model configuration
segmentation_data_ingestion:
  root_dir: artifacts/segmentation/data_ingestion
  data_version_dir: artifacts/segmentation/data_version
  local_data_file: artifacts/segmentation/data_ingestion/input_raw.csv
  test_size: 0.2
  random_state: 42
  bucket_name: ml-dataversion

segmentation_prepare_base_model:
  model_version_dir: artifacts/segmentation/model_version
  data_version_dir: artifacts/segmentation/data_version
  random_state: 42

segmentation_training:
  model_version_dir: artifacts/segmentation/model_version
  data_version_dir: artifacts/segmentation/data_version

segmentation_evaluation:
  model_version_dir: artifacts/segmentation/model_version
  data_version_dir: artifacts/segmentation/data_version
  evaluation_dir: artifacts/segmentation/evaluation

segmentation_cloud_storage_push:
  root_dir: artifacts
  bucket_name: segmentationdataversion
  data_version_dir: artifacts/segmentation/data_version  
  evaluation_dir: artifacts/segmentation/evaluation 

segmentation_mlflow_config:
  dagshub_username: Teungtran
  dagshub_repo_name: segmentation_mlops
  tracking_uri: https://dagshub.com/Teungtran/segmentation_mlops.mlflow
  experiment_name: Segmentation_model_training_cycle

# TimeSeries model configuration
timeseries_data_ingestion:
  root_dir: artifacts/timeseries/data_ingestion
  data_version_dir: artifacts/timeseries/data_version
  local_data_file: artifacts/timeseries/data_ingestion/input_raw.csv
  test_size: 0.2
  random_state: 42
  bucket_name: ml-dataversion

timeseries_prepare_base_model:
  model_version_dir: artifacts/timeseries/model_version
  data_version_dir: artifacts/timeseries/data_version
  random_state: 42

timeseries_training:
  model_version_dir: artifacts/timeseries/model_version
  data_version_dir: artifacts/timeseries/data_version

timeseries_evaluation:
  model_version_dir: artifacts/timeseries/model_version
  data_version_dir: artifacts/timeseries/data_version
  evaluation_dir: artifacts/timeseries/evaluation

timeseries_cloud_storage_push:
  root_dir: artifacts
  bucket_name: ml-dataversion
  data_version_dir: artifacts/timeseries/data_version  
  evaluation_dir: artifacts/timeseries/evaluation 

timeseries_mlflow_config:
  dagshub_username: Teungtran
  dagshub_repo_name: timeseries_mlops
  tracking_uri: https://dagshub.com/Teungtran/timeseries_mlops.mlflow
  experiment_name: TimeSeries_model_training_cycle