[project]
name = "be-preprocess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asgi-correlation-id>=4.3.4",
    "beautifulsoup4>=4.13.4",
    "boto3>=1.40.2",
    "cloudscraper>=1.2.71",
    "fastapi>=0.116.1",
    "httpx>=0.27.0",
    "langchain>=0.3.27",
    "langchain-community>=0.3.27",
    "langchain-core>=0.3.72",
    "langchain-experimental>=0.3.4",
    "langchain-openai>=0.3.28",
    "langchain-qdrant>=0.2.0",
    "langchain-text-splitters>=0.3.9",
    "markitdown[az-doc-intel]>=0.0.1a2",
    "pydantic>=2.11.7",
    "pymupdf>=1.26.3",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "qdrant-client>=1.15.1",
    "requests>=2.32.4",
    "sqlalchemy>=2.0.42",
    "structlog>=25.4.0",
    "typing-extensions>=4.14.1",
    "uvicorn>=0.35.0",
]
