embedding_model_config:
  provider: "openai"
  model: "text-embedding-3-small"
  # kwargs for EmbeddingModel
  kwargs:
    chunk_size: 1000

chat_model_config:
  provider: "openai"
  model: "gpt-4o-mini"
  top_k: 10
  kwargs:
    temperature: 0
    max_tokens: 3000
    top_p: 0.7
    streaming: True
    max_retries: 1

chunking_method_config:
  method: "table"
  chunk_size: 2000
  chunk_overlap: 100

retrieval_config:
  provider: "qdrant"

preprocessing_config:
  output_folder: "../assets/preprocessed"