import os
import re
import json
import warnings
from textwrap import dedent
from typing import Dict
import numpy as np
import pandas as pd
from langchain_openai import ChatOpenAI
warnings.filterwarnings("ignore", category=FutureWarning)
from pydantic import SecretStr
from langchain_openai import ChatOpenAI
from app.config.base_config import OpenAIConfig
from typing import Callable
chat_config = OpenAIConfig()

api_key = chat_config.api_key
if isinstance(api_key, Callable):
    api_key = api_key()  
if isinstance(api_key, SecretStr):  
    api_key = api_key.get_secret_value()
def ai_model():
    return ChatOpenAI(
        openai_api_key=api_key,
        model="gpt-4o-mini",
        temperature=0
    )
llm = ai_model()
def extract_python_code(text: str) -> str:
    """Extract Python code from LLM response, handling various formats"""
    pattern = r"```(?:python)?\s*(.*?)```"
    matches = re.findall(pattern, text, re.DOTALL)
    if matches:
        return matches[0].strip()
    return text.strip()


def execute_pandas_code(code: str, df: pd.DataFrame) -> dict:
    """
    Safely execute pandas code generated by LLM
    
    Returns:
        dict with 'success', 'result', and optional 'error' keys
    """
    lines = code.split('\n')
    fixed_lines = []
    for line in lines:
        if 'result' in line and line.startswith('    '):
            fixed_lines.append(line)
        else:
            fixed_lines.append(line)
    fixed_code = '\n'.join(fixed_lines)

    safe_globals = {
        'pd': pd,
        'np': np,
        'df': df,
        'len': len,
        'int': int,
        'float': float,
        'str': str,
        'round': round,
        'range': range,
        'dict': dict,
        'list': list,
        'result': None,
    }

    safe_locals = {}

    try:
        exec(fixed_code, safe_globals, safe_locals)
        if 'result' in safe_locals:
            result_value = safe_locals['result']
        elif 'result' in safe_globals:
            result_value = safe_globals['result']
        else:
            return {
                'success': False,
                'result': "Code executed but no 'result' variable was defined.",
                'code': code
            }
        if result_value is None:
            return {
                'success': False,
                'result': None,
                'code': code
            }
        return {
            'success': True,
            'result': result_value,
            'code': code
        }
    except Exception as e:
        return {
            'success': False,
            'result': str(e),
            'code': code
        }


def generate_pandas_code(user_input: str, df_sample: str, data_info):
    """
    Generates pandas code to answer user's question.
    """
    prompt = dedent(f"""

    Follow these steps to generate **pandas code** for the user's question.

    User Question: {user_input}

    ### STEP 1: UNDERSTAND THE DATA

    **ACTUAL DATA INFORMATION (columns that exist):**  
    {data_info}

    **Sample:**  
    {df_sample}

    ## STEP 2: DESCRIBE COLUMNS

        Write short, clear **description** for each column likely represents and how it might be useful for analysis.  
        Use your best judgment from the column names and sample data.

    ## STEP 3: GENERATE PANDAS CODE

        **Generate simple, clear pandas code following these rules:**

        1. Always start with necessary imports (`import pandas as pd`).
        2. Work directly on `df` (no new variables like `df_temp`).
        3. Convert all column names to lowercase.
        4. Convert timestamp columns using `pd.to_datetime` if present.
        5. Use only columns that exist in the dataset.
        6. Implement logic directly — no complex structures, loops, or helper functions.
        7. The final output must be a dictionary named `result`.
        8. Make the logic reflect the user’s question (sum, mean, filter, count, compare, etc.).
        9. Keep the code short, clean, and executable.
        
    ## NOTE When generating the code, **try to gather as much relevant information as possible** from the data that supports the user’s question.  

        **Guidelines:**
        - If the user asks about **averages**, also include totals, maximums, and minimums.  
        - If the question mentions **a specific vehicle type**, include comparisons with other related vehicle columns.  
        - If the question refers to **time**, include hourly or daily breakdowns and surrounding context.  
        - If it mentions **anomalies**, include counts and proportions for each relevant anomaly column.  
        - Always add at least **3–5 relevant metrics** that help explain or support the main query.

        **Goal:**  
        Provide **comprehensive insights**, not just a single number or value.
        
    ## STEP 5: OUTPUT FORMAT

        Return only executable Python code (no markdown or explanations).
        Store all final values in a single dictionary named result.

        result = {...}
        
    ## EXAMPLE:
    import pandas as pd

    # Convert column names to lowercase
    df.columns = df.columns.str.lower()
        
    /// Then write your code here
    
    """)
    try:
        response = llm.invoke(prompt)
        code = response.content if hasattr(response, "content") else str(response)
        code = code.strip()

        # Remove markdown code blocks if present
        if code.startswith("```python"):
            code = code.split("```python", 1)[1]
        if code.startswith("```"):
            code = code.split("```", 1)[1]
        if code.endswith("```"):
            code = code.rsplit("```", 1)[0]

        code = code.strip()
        return code
    except Exception as e:
        raise Exception(f"Failed to generate code: {str(e)}")


def verify_result(result: Dict) -> Dict:
    """
    Uses an LLM to verify if the result contains any error messages.
    If errors are found, sets success to False.
    """
    prompt = f"""Analyze this execution result and determine if it contains any error messages or exceptions.

            Result data:
            {result.get('result')}

            Code that was executed:
            {result.get('code')}

            Reply with ONLY "ERROR_FOUND" if there are any errors, exceptions, or error messages.
            Reply with ONLY "NO_ERROR" if everything looks successful.
            """
    message = llm.invoke(prompt)
    llm_response = message.content
    if "ERROR_FOUND" in llm_response:
        result['success'] = False
    return result


def format_result(result: any) -> str:
    """Format the execution result into a readable string"""
    if isinstance(result, pd.DataFrame):
        if len(result) > 20:
            return f"Result DataFrame ({len(result)} rows x {len(result.columns)} columns):\n\n{result.head(10).to_string()}\n\n... (showing first 10 rows)"
        return f"Result DataFrame:\n\n{result.to_string()}"
    elif isinstance(result, pd.Series):
        if len(result) > 20:
            return f"Result Series ({len(result)} values):\n\n{result.head(10).to_string()}\n\n... (showing first 10 values)"
        return f"Result Series:\n\n{result.to_string()}"
    elif isinstance(result, (dict, list)):
        return json.dumps(result, indent=2, default=str)
    else:
        return str(result)



def analyze_tool(user_input: str, df: pd.DataFrame):
    """
    Main data analysis tool that processes user questions about the dataset.
    
    Returns:
        tuple: (answer, generated_code)
            - answer: JSON string containing summary, raw_data, and code
            - generated_code: str, the code that was executed
    """
    df_sample = df.head(5).to_string()
    df_info = df.info()
    try:
        generated_code = generate_pandas_code(
            user_input=user_input.lower().strip(),
            df_sample=df_sample,
            data_info=df_info
        )

        execution_result = execute_pandas_code(generated_code, df)
        verifyed_result = verify_result(execution_result)

        print(f"DEBUG: Initial execution result: {execution_result}")
        print(f"DEBUG: Verified result: {verifyed_result}")

        if not verifyed_result["success"]:
            retry_prompt = dedent(f"""
            The previous code execution FAILED.

            Failed code:
            {generated_code}

            Error message:
            {execution_result.get('error', 'Unknown error')}

            === YOUR TASK ===
            1. ANALYZE the error type: {execution_result.get('error', 'Unknown')}
            2. IDENTIFY the root cause and FIX IT.
            3. Common fixes needed:
                - Check indentation (result variable must be at module level)
                - Ensure 'result' is defined in ALL code paths (if/else)
                - Initialize result = None at the start if needed
            4. GENERATE NEW CODE that:
                - Fixes the error COMPLETELY
                - Defines 'result' variable at module level (no indentation)
                - Avoids undefined variables or bad column names
                - Uses simple scalar variables (int, float, str)
                - No lambdas, dict chaining
                
            === OUTPUT ===
            Return ONLY valid Python code storing final output in `result`.
            Make sure `result` is defined at the module level (no indentation before it).
            """)

            try:
                generated_code = generate_pandas_code(
                    user_input=user_input.lower() + "\n\n" + retry_prompt,
                    df_sample=df_sample,
                    data_info=df_info
                )

                execution_result = execute_pandas_code(generated_code, df)
                verifyed_result = verify_result(execution_result)

            except Exception as e:
                error_msg = (
                    f"Error: Unable to generate working code. "
                    f"Original error: {execution_result.get('error', 'Unknown')}"
                )
                return (error_msg, generated_code)

        if verifyed_result["success"]:
            result_data = verifyed_result["result"]
            formatted_result = format_result(result_data)
            return formatted_result

    except Exception as e:
        raise e
