import os
import re
import json
import warnings
from textwrap import dedent
from typing import Dict
import numpy as np
import pandas as pd
from langchain_openai import ChatOpenAI
warnings.filterwarnings("ignore", category=FutureWarning)
from pydantic import SecretStr
from langchain_openai import ChatOpenAI
from app.config.base_config import OpenAIConfig
from typing import Callable
chat_config = OpenAIConfig()

api_key = chat_config.api_key
if isinstance(api_key, Callable):
    api_key = api_key()  
if isinstance(api_key, SecretStr):  
    api_key = api_key.get_secret_value()
def ai_model():
    return ChatOpenAI(
        openai_api_key=api_key,
        model="gpt-4.1-mini",
        temperature=0
    )
llm = ai_model()
def extract_python_code(text: str) -> str:
    """Extract Python code from LLM response, handling various formats"""
    pattern = r"```(?:python)?\s*(.*?)```"
    matches = re.findall(pattern, text, re.DOTALL)
    if matches:
        return matches[0].strip()
    return text.strip()


def execute_pandas_code(code: str, df: pd.DataFrame) -> dict:
    """
    Safely execute pandas code generated by LLM
    
    Returns:
        dict with 'success', 'result', and optional 'error' keys
    """
    lines = code.split('\n')
    fixed_lines = []
    for line in lines:
        if 'result' in line and line.startswith('    '):
            fixed_lines.append(line)
        else:
            fixed_lines.append(line)
    fixed_code = '\n'.join(fixed_lines)

    safe_globals = {
        'pd': pd,
        'np': np,
        'df': df,
        'len': len,
        'int': int,
        'float': float,
        'str': str,
        'round': round,
        'range': range,
        'dict': dict,
        'list': list,
        'result': None,
    }

    safe_locals = {}

    try:
        exec(fixed_code, safe_globals, safe_locals)
        if 'result' in safe_locals:
            result_value = safe_locals['result']
        elif 'result' in safe_globals:
            result_value = safe_globals['result']
        else:
            return {
                'success': False,
                'result': "Code executed but no 'result' variable was defined.",
                'code': code
            }
        if result_value is None:
            return {
                'success': False,
                'result': "Result is None. Make sure to assign a string value to 'result'.",
                'code': code
            }
        # Ensure result is always a string
        if not isinstance(result_value, str):
            result_value = str(result_value)
        
        return {
            'success': True,
            'result': result_value,
            'code': code
        }
    except Exception as e:
        return {
            'success': False,
            'result': str(e),
            'code': code
        }


def generate_pandas_code(user_input: str, df_sample: str, data_info):
    """
    Generates pandas code to answer user's question.
    """
    prompt = dedent(f"""

    Follow these steps to generate **pandas code** for the user's question.

    User Question: {user_input}

    ### STEP 1: UNDERSTAND THE DATA

    **ACTUAL DATA INFORMATION (ONLY USE THESE COLUMNS - DO NOT CREATE OR ASSUME COLUMNS):**  
    {data_info}

    **Sample Data (first 5 rows):**  
    {df_sample}

    ## STEP 2: IDENTIFY RELEVANT COLUMNS

        **CRITICAL**: You MUST only use column names that appear in the data_info above.
        - Match user query keywords to column names (case-insensitive, partial matches OK)
        - Use the sample data above to see examples of actual values in columns
        - The sample data shows real values, so you can see what format/names are actually used

    ## STEP 3: GENERATE PANDAS CODE

        **Generate simple, clear pandas code following these rules:**

        1. Always start with necessary imports (`import pandas as pd`).
        2. Convert all column names to lowercase first: `df.columns = df.columns.str.lower()`
        3. **CRITICAL**: ONLY use column names from the data_info above. DO NOT assume column names exist.
        4. **CRITICAL**: Before using specific values (like "VIP", "Regular"), FIRST check what values actually exist in the column:
            - Use `df['column_name'].unique()` or `df['column_name'].value_counts()` to see actual values
            - Match user query terms to actual values in the column (case-insensitive)
            - Use `.get()` with default 0 when accessing value_counts to handle missing values safely
        5. Convert timestamp columns using `pd.to_datetime` if present.
        6. Work directly on `df` (no new variables like `df_temp`).
        7. Implement logic directly — no complex structures, loops, or helper functions.
        8. **CRITICAL**: The final output MUST be a STRING variable named `result`.
        9. Make the logic reflect the user's question (sum, mean, filter, count, compare, etc.).
        10. Keep the code short, clean, and executable.
        11. **CRITICAL**: DO NOT create dictionaries, lists, or any complex data structures.
        12. **CRITICAL**: For multiple results, concatenate them into a single string using + or f-strings.
        13. **CRITICAL**: Use len(df) for total count, NOT df['column'].nunique() unless specifically asked for unique values.
        14. For counts: First get value_counts(), then use `.get('actual_value', 0)` to safely access counts.
        15. For percentages: calculate as (count / total) * 100 and convert to float(), then format as string.
        16. Always convert numbers to strings using str() or f-strings before concatenating.
        17. **IMPORTANT**: When matching user query terms to column values, use case-insensitive matching or check multiple variations.
        
    ## NOTE When generating the code, **try to gather as much relevant information as possible** from the data that supports the user's question.  

        **Guidelines:**
        - If the user asks about **averages**, also include totals, maximums, and minimums.  
        - If the question mentions **a specific vehicle type**, include comparisons with other related vehicle columns.  
        - If the question refers to **time**, include hourly or daily breakdowns and surrounding context.  
        - If it mentions **anomalies**, include counts and proportions for each relevant anomaly column.  
        - Always add at least **3–5 relevant metrics** that help explain or support the main query.
        - Concatenate all findings into one clear, readable string.

        **Goal:**  
        Provide **comprehensive insights** as a single formatted string, not just a single number or value.
        
    ## STEP 5: OUTPUT FORMAT

        Return only executable Python code (no markdown or explanations).
        Store all final values in a single STRING variable named result.
        Use string concatenation or f-strings to combine multiple findings.

        result = "Metric 1: value1, Metric 2: value2, ..."
        
    ## EXAMPLE 1: Distribution analysis with value matching (when user mentions specific categories)
    import pandas as pd

    # Convert column names to lowercase
    df.columns = df.columns.str.lower()
    
    # Get value counts for the relevant column (match column name from data_info)
    counts = df['customer_labels'].value_counts()
    
    # Match user query terms to actual values (case-insensitive, partial match)
    # Iterate through actual values to find matches - this is acceptable for value matching
    vip_count = 0
    regular_count = 0
    for val, count in counts.items():
        val_lower = str(val).lower()
        if 'vip' in val_lower:
            vip_count += int(count)
        elif 'regular' in val_lower:
            regular_count += int(count)
    
    total_rows = len(df)
    vip_percentage = float((vip_count / total_rows) * 100) if total_rows > 0 else 0.0
    regular_percentage = float((regular_count / total_rows) * 100) if total_rows > 0 else 0.0
    
    result = f"VIP count: {{vip_count}}, Regular count: {{regular_count}}, Total count: {{total_rows}}, VIP percentage: {{vip_percentage:.2f}}%, Regular percentage: {{regular_percentage:.2f}}%"

    ## EXAMPLE 2: Simple count (when exact values match)
    import pandas as pd

    df.columns = df.columns.str.lower()
    counts = df['status'].value_counts()
    active_count = int(counts.get('active', 0))
    inactive_count = int(counts.get('inactive', 0))
    total = len(df)
    
    result = f"Active: {{active_count}}, Inactive: {{inactive_count}}, Total: {{total}}"

    ## EXAMPLE 3: Numeric analysis (using columns from data_info)
    import pandas as pd

    df.columns = df.columns.str.lower()
    avg_value = float(df['price'].mean()) if 'price' in df.columns else 0.0
    max_value = float(df['price'].max()) if 'price' in df.columns else 0.0
    min_value = float(df['price'].min()) if 'price' in df.columns else 0.0
    total = len(df)
    
    result = f"Average price: {{avg_value:.2f}}, Max price: {{max_value:.2f}}, Min price: {{min_value:.2f}}, Total records: {{total}}"
    
    """)
    try:
        response = llm.invoke(prompt)
        code = response.content if hasattr(response, "content") else str(response)
        code = code.strip()

        # Remove markdown code blocks if present
        if code.startswith("```python"):
            code = code.split("```python", 1)[1]
        if code.startswith("```"):
            code = code.split("```", 1)[1]
        if code.endswith("```"):
            code = code.rsplit("```", 1)[0]

        code = code.strip()
        return code
    except Exception as e:
        raise Exception(f"Failed to generate code: {str(e)}")


def verify_result(result: Dict) -> Dict:
    """
    Verifies if the result contains any error messages.
    If errors are found, sets success to False.
    """
    # If success is already False, don't override it
    if not result.get('success', True):
        return result
    
    result_data = result.get('result')
    
    # Result should always be a string now
    if not isinstance(result_data, str):
        # Convert to string if it's not already
        result_data = str(result_data)
        result['result'] = result_data
    
    # Check for error keywords in the string result
    error_keywords = ['error', 'exception', 'traceback', 'failed', 'cannot', 'invalid', 'not found', 'undefined', 'code executed but no', 'result is none']
    if any(keyword in result_data.lower() for keyword in error_keywords):
        result['success'] = False
        return result
    
    # If result is a non-empty string without error keywords, it's valid
    if result_data and result_data.strip():
        return result
    
    # Empty string might be an issue
    if not result_data or not result_data.strip():
        result['success'] = False
        result['result'] = "Result is empty. Make sure to assign a non-empty string value to 'result'."
    
    return result


def format_result(result: any) -> str:
    """Format the execution result into a readable string"""
    if isinstance(result, pd.DataFrame):
        if len(result) > 20:
            return f"Result DataFrame ({len(result)} rows x {len(result.columns)} columns):\n\n{result.head(10).to_string()}\n\n... (showing first 10 rows)"
        return f"Result DataFrame:\n\n{result.to_string()}"
    elif isinstance(result, pd.Series):
        if len(result) > 20:
            return f"Result Series ({len(result)} values):\n\n{result.head(10).to_string()}\n\n... (showing first 10 values)"
        return f"Result Series:\n\n{result.to_string()}"
    elif isinstance(result, (dict, list)):
        return json.dumps(result, indent=2, default=str)
    else:
        return str(result)



def analyze_tool(user_input: str, df: pd.DataFrame):
    """
    Main data analysis tool that processes user questions about the dataset.
    
    Returns:
        tuple: (answer, generated_code)
            - answer: JSON string containing summary, raw_data, and code
            - generated_code: str, the code that was executed
    """
    df_sample = df.head(5).to_string()
    df_info = df.info()
    try:
        generated_code = generate_pandas_code(
            user_input=user_input.lower().strip(),
            df_sample=df_sample,
            data_info=df_info
        )

        execution_result = execute_pandas_code(generated_code, df)
        verifyed_result = verify_result(execution_result)

        print(f"DEBUG: Initial execution result: {execution_result}")
        print(f"DEBUG: Verified result: {verifyed_result}")

        if not verifyed_result["success"]:
            retry_prompt = dedent(f"""
            The previous code execution FAILED.

            Failed code:
            {generated_code}

            Error message:
            {execution_result.get('error', 'Unknown error')}

            === YOUR TASK ===
            1. ANALYZE the error type: {execution_result.get('result', 'Unknown error')}
            2. IDENTIFY the root cause and FIX IT.
            3. Common fixes needed:
                - Check indentation (result variable must be at module level)
                - Ensure 'result' is defined in ALL code paths (if/else)
                - **CRITICAL**: 'result' MUST be a STRING, NOT a dictionary, list, or any other data type
                - **CRITICAL**: ONLY use column names from the data_info provided. DO NOT assume column names exist.
                - **CRITICAL**: Before using specific values (like "VIP", "Regular"), FIRST check what values actually exist in the column using value_counts() or unique()
                - Match user query terms to actual column values using case-insensitive matching
                - For multiple values, concatenate them into a single string using f-strings or +
                - DO NOT use .to_dict(), .to_list() or any pandas conversion methods
                - Use len(df) for total count, NOT .nunique() unless specifically needed
            4. GENERATE NEW CODE that:
                - Fixes the error COMPLETELY
                - Defines 'result' as a STRING variable at module level (no indentation)
                - Uses ONLY column names from data_info (check the data_info provided)
                - First checks actual values in columns before matching to user query terms
                - Uses case-insensitive matching when matching user query terms to column values
                - Avoids undefined variables or bad column names
                - Concatenates all findings into one string (e.g., result = f"Metric1: {{value1}}, Metric2: {{value2}}")
                - NO dictionaries, NO lists, NO .to_dict(), NO .to_list(), NO lambdas, NO dict chaining
                - Convert all numbers to strings using str() or f-strings before concatenating
                
            === OUTPUT ===
            Return ONLY valid Python code storing final output as a STRING in `result`.
            Make sure `result` is a string variable defined at the module level (no indentation before it).
            Example: result = f"Total: {{total}}, Average: {{avg:.2f}}"
            
            === REMEMBER ===
            - Match user query keywords to column names from data_info (case-insensitive, partial matches OK)
            - Check actual values in columns before using them
            - Use iteration over value_counts() items when you need to match user query terms to actual values
            """)

            try:
                generated_code = generate_pandas_code(
                    user_input=user_input.lower() + "\n\n" + retry_prompt,
                    df_sample=df_sample,
                    data_info=df_info
                )

                execution_result = execute_pandas_code(generated_code, df)
                verifyed_result = verify_result(execution_result)

            except Exception as e:
                error_msg = (
                    f"Error: Unable to generate working code. "
                    f"Original error: {execution_result.get('error', 'Unknown')}"
                )
                return (error_msg, generated_code)

        if verifyed_result["success"]:
            result_data = verifyed_result["result"]
            formatted_result = format_result(result_data)
            return formatted_result

    except Exception as e:
        raise e
